# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        # Assuming your project is not a Swift Package Manager project
        # If it is, you should have a Package.swift file already
        # If not, you can create an empty Package.swift file
        echo 'import PackageDescription; let package = Package(name: "YourProjectName")' > Package.swift

        # Build your project
        swift build -v

    - name: Run tests
      run: swift test -v
